# Generated by Django 3.0 on 2021-06-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210629_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorization',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
