# Generated by Django 3.0 on 2021-05-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovativeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=2000)),
                ('posted_by', models.CharField(max_length=25)),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestOnCrih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=2000)),
                ('posted_by', models.CharField(max_length=25)),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
