# Generated by Django 3.0 on 2021-05-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestoncrih',
            old_name='update_date',
            new_name='Deadline',
        ),
    ]
