# Generated by Django 3.0 on 2021-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0003_auto_20210618_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestoncrih',
            name='deadline',
            field=models.DateField(),
        ),
    ]
