# Generated by Django 3.0 on 2021-06-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0004_auto_20210618_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestoncrih',
            old_name='image_url',
            new_name='image',
        ),
    ]
