# Generated by Django 3.0 on 2021-06-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0006_latest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestOnCrih',
        ),
    ]
