# Generated by Django 3.0 on 2021-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0007_delete_latestoncrih'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningLatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(default='default.jpg', upload_to='opportunity_photos')),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='InnovativeNews',
        ),
        migrations.DeleteModel(
            name='Sidebar1',
        ),
        migrations.DeleteModel(
            name='Sidebar2',
        ),
    ]
