# Generated by Django 3.0 on 2021-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0009_auto_20210625_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
