# Generated by Django 3.0 on 2021-06-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crihhome', '0011_conferencenfellowships_grantsncontest_internshipsnscholarships_medicalinnovationcourses_researchcour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinnovationcourses',
            name='deadline',
        ),
    ]
